### ISSUE TITLE
I18nFilter: LocaleUtils.toLocale(String str) throws exception on invalid locale parameter

### ISSUE THREAD

**Issue by opncow** [lightoze/gwt-i18n-server#21]
GWT falls back to the default locale on the client side if an invalid one is given. The I18nFilter doesn't do that. Is this as intended? I would have put a try/catch around  `LocaleUtils.toLocale(String str)`.

**Comment by lightoze** [comment]
You are speaking about `I18nFilter`, right? It's not intentional, it just never was the case - normally locale is chosen from a limited set of options all of which are valid.

**Comment by opncow** [comment]
Yep, I'm speaking about `I18nFilter`. You are right, this just happens when one enters a wrong locale parameter value by hand. I'm not sure if it is better to throw this exception or to fall back to something. For my application this actually is not a real problem, users shouldn't mess with the URL. :-)

**Comment by lightoze** [comment]
OK, then I'll leave the issue open and make it behave like GWT on occasion.

**Comment by lightoze** [comment]
Just released version 0.23 which fixes this bug along with other changes.
