### ISSUE TITLE
Also look for properties files in root package

### ISSUE THREAD

**Issue by vovcacik** [lightoze/gwt-i18n-server#22]
Hi,
I've noticed that `LocaleProxy.loadBundle(Class clazz, String locale)` searches for properties files only in the package of the `clazz` and its super classes. GWT 2.7 (and I strongly believe that same applies to 2.6) also searches the root package.

You probably dont want to run this in `loadBundle` as it would process the same bundle for each super class, but it should get incorporated in the dereferencing process:

```
InputStream stream = getClassLoader().getResourceAsStream(clazz.getSimpleName() + (locale == null?"":"_" + locale) + ".properties")
```

**Comment by lightoze** [comment]
I could not make GWT load properties from root package. Do you have a working example, or even better a reference to GWT documentation/source where it is stated? Maybe you have some custom configuration which makes it work?

**Comment by vovcacik** [comment]
I have also tried to load properties from root package, but it seems I am not able to reproduce it. It is possible that I didn't really meant root package, but rather the package where app's entry point class is.

Gwt looks for `.properties` file in entry class package, this feature is documented as:

> Begin by creating a default properties file called MyConstants.properties in your GWT project. You can place the file anywhere in your module’s source path, but the .properties file and corresponding interface must be in the same package. It’s fine to place the file in the same package as your module’s entry point class.

[source](http://www.gwtproject.org/doc/latest/DevGuideI18nConstants.html)

I was fairly sure it was root package, I also have foggy recollection of browsing gwt's code, but it seems my memory failed me here.
